### PR TITLE
@grol is alternative to !grol. bot now uses "reply" to identify origin. complex messages sending and interactions update/replies

### LINKED ISSUE #63: refactor create/update/delete
possibly

              I guess I could probably pass only the inner message to handle message

_Originally posted by @ldemailly in https://github.com/grol-io/grol-discord-bot/pull/56#discussion_r1715418520_

### PR DESCRIPTION
**Pull request by ldemailly**
Reply and @ tag example:

Screenshot 2024-08-24 at 4 42 30 PM

Depends on https://github.com/grol-io/grol/pull/178

```go
func discordMessage(){
	msg= {
	  "content": "A test...",
	  "components":	[discord.actionRow([
				discord.button("Option 1", discord.buttonStyle.primary, "option_1"),
				discord.button("Option 2", discord.buttonStyle.secondary, "option_2")
	  ])]
	}
	ChannelMessageSendComplex(msg) // returns the msg id
}
```

then DM `raw`

and get

Screenshot 2024-08-23 at 4 45 37 PM

(see discord_message.gr)

Also:
Fixes #63

### CODE REVIEW

**Comment by ldemailly** [comment]
With this 
```go
func discordMessage(chanID){
	msg= {
	  "content": "A test...",
	  "components": [
		{
		  "type": 1,
		  "components": [
			{
			  "type": 2,
			  "label": "Option 1",
			  "style": 1,
			  "custom_id": "option_1"
			},
			{
			  "type": 2,
			  "label": "Option 2",
			  "style": 1,
			  "custom_id": "option_2"
			}
		  ]
		}
	  ]
	}
	ChannelMessageSendComplex(chanID,msg) // returns the msg id
}
```

and the `raw` test message:

Screenshot 2024-08-22 at 9 44 03 PM

**Comment by ldemailly** [comment]
depends on grol-io/grol#175

**Comment by ldemailly** [comment]
Screenshot 2024-08-25 at 11 36 06 AM
🎉

**Comment by ldemailly** [comment]
Fully functional interactions:

Screenshot 2024-08-25 at 5 19 36 PM

**Review by ccoVeille — COMMENTED** [review]
LGTM 👍

**Pull request merged**
